spring.application.name=Sportradar Coding Academy Coding Exercise BE
spring.datasource.url =jdbc:postgresql://localhost:5432/Calendar
spring.datasource.username=postgres
spring.datasource.password=1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true